AWSTemplateFormatVersion: 2010-09-09
Description: Bastion template for Project X

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Network Configuration
      Parameters:
      - VpcId
      - VPCSubnetID
      - SSHRemoteAccessCIDR
      - BastionKeyPairName
      - BastionImageId
      - BastionInstanceType

Parameters:
  VpcId:
    Description: A VPC ID
    Type: String
  VPCSubnetID:
    Description: A VPC subnet ID
    Type: String
  SSHRemoteAccessCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: Allowed CIDR block for external SSH access to the bastions
    Type: String
  BastionKeyPairName: 
    Description: Amazon EC2 Key Pair
    Type: "AWS::EC2::KeyPair::KeyName"
    ConstraintDescription: must be a valid Key Pair
  BastionImageId:
    Description: Valid Amazon EC2 AMI Id
    Type: String
    Default: ami-040589e8273e08d6e
  BastionInstanceType:
    Description: Valid Amazon EC2 Instance Type
    Type: String
    Default: t4g.micro

Resources:
  BastionSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref SSHRemoteAccessCIDR
      Tags:
        - Key: Name
          Value: ProjectXBastionSG

  BastionHost:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref BastionImageId
      InstanceType: !Ref BastionInstanceType
      KeyName: !Ref BastionKeyPairName
      SubnetId: !Ref VPCSubnetID
      SecurityGroupIds: 
        - !Ref BastionSecurityGroup
      Tags:
        - Key: Name
          Value: ProjectXBastionHost

Outputs:
  BastionHostDNS:
    Description: Bastion host public DNS
    Value: !GetAtt BastionHost.PublicDnsName
  BastionPublicIPAddress:
    Description: Bastion host public IP
    Value: !GetAtt BastionHost.PublicIp
  BastionSG:
    Description: Bastion security group
    Value: !Ref BastionSecurityGroup