
AWSTemplateFormatVersion: 2010-09-09
Description: VPC template for Project X

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Network Configuration
      Parameters:
      - VpcCIDR
      - PublicSubnet1CIDR
      - PublicSubnet2CIDR
      - PublicSubnet3CIDR
      - PrivateSubnet1CIDR
      - PrivateSubnet2CIDR
      - PrivateSubnet3CIDR
      - SSHRemoteAccessCIDR
      - ALBAccessCIDR
      - BuildAgilePartnerCert
      - AgilePartnerCert
    - Label:
        default: App Instance Configuration
      Parameters:
      - OperatorEMail
      - AppImageId
      - AppInstanceType
      - BastionImageId
      - BastionInstanceType
      - BastionKeyPairName
    - Label:
        default: "RDS Configuration"
      Parameters:
      - DBInstanceClass
      - DBAllocatedStorage
      - DBName
      - DBUser
      - DBPassword
      - MultiAZDatabase

Parameters:
  VpcCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid IP range in x.x.x.x/x notation
    Default: 10.0.0.0/16
    Description: CIDR Block for the VPC
    Type: String
  PublicSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid IP range in x.x.x.x/x notation
    Default: 10.0.1.0/24
    Description: CIDR Block for the public DMZ subnet 1 located in Availability Zone 1
    Type: String
  PublicSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid IP range in x.x.x.x/x notation
    Default: 10.0.2.0/24
    Description: CIDR Block for the public DMZ subnet 2 located in Availability Zone 2
    Type: String
  PublicSubnet3CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid IP range in x.x.x.x/x notation
    Default: 10.0.3.0/24
    Description: CIDR Block for the public DMZ subnet 3 located in Availability Zone 3
    Type: String
  PrivateSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid IP range in x.x.x.x/x notation
    Default: 10.0.10.0/24
    Description: CIDR block for private subnet 1 located in Availability Zone 1
    Type: String
  PrivateSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid IP range in x.x.x.x/x notation
    Default: 10.0.11.0/24
    Description: CIDR block for private subnet 2 located in Availability Zone 2
    Type: String
  PrivateSubnet3CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid IP range in x.x.x.x/x notation
    Default: 10.0.12.0/24
    Description: CIDR block for private subnet 3 located in Availability Zone 3
    Type: String
  SSHRemoteAccessCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: Allowed CIDR block for external SSH access to the bastions
    Type: String
  BastionKeyPairName: 
    Description: Amazon EC2 Key Pair
    Type: "AWS::EC2::KeyPair::KeyName"
    ConstraintDescription: must be a valid Key Pair
  ALBAccessCIDR:
    Description: ALB access CIDR
    Type: String
    Default: 0.0.0.0/0
  BuildAgilePartnerCert:
    Description: Do you have a valid SSL?
    Type: String
    Default: False
    AllowedValues:
    - True
    - False
  AgilePartnerCert:
    Description: Agile Partner SSL Certificate ARN
    Type: String
    ConstraintDescription: must be a valid Certificate ARN
  BastionImageId:
    Description: Valid Amazon EC2 AMI Id
    Type: String
    Default: ami-040589e8273e08d6e
  BastionInstanceType:
    Description: Valid Amazon EC2 Instance Type
    Type: String
    Default: t4g.micro
  AppImageId:
    Description: Valid AMI for ALB
    Type: String
    Default: ami-040589e8273e08d6e
  AppInstanceType:
    Description: Valid EC2 Instance Type for ALB
    Type: String
    Default: t4g.micro
  DBName:
    Default: myDatabase
    Description: MySQL database name
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBUser:
    NoEcho: 'true'
    Description: Username for MySQL database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    NoEcho: 'true'
    Description: Password for MySQL database access
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
  DBAllocatedStorage:
    Default: '5'
    Description: The size of the database (Gb)
    Type: Number
    MinValue: '5'
    MaxValue: '1024'
    ConstraintDescription: must be between 5 and 1024Gb.
  DBInstanceClass:
    Description: The database instance type
    Type: String
    Default: db.t2.micro
  MultiAZDatabase:
    Default: 'true'
    Description: Create a Multi-AZ MySQL Amazon RDS database instance
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    ConstraintDescription: must be either true or false.
  OperatorEMail:
    Description: EMail address to notify if there are any scaling operations
    Type: String
    AllowedPattern: ([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)
    ConstraintDescription: must be a valid email address.

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://umdaa-cloud-trial-trailbucket-utvblevzzv2v.s3.ap-south-1.amazonaws.com/Template/vpc.yaml
      Parameters:
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR
        PrivateSubnet3CIDR: !Ref PrivateSubnet3CIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        PublicSubnet3CIDR: !Ref PublicSubnet3CIDR
        VpcCIDR: !Ref VpcCIDR
  BastionStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://umdaa-cloud-trial-trailbucket-utvblevzzv2v.s3.ap-south-1.amazonaws.com/Template/bastion.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.ProjectXDVpcId
        VPCSubnetID: !GetAtt VPCStack.Outputs.ProjectXPublic1
        SSHRemoteAccessCIDR: !Ref SSHRemoteAccessCIDR
        BastionKeyPairName: !Ref BastionKeyPairName
        BastionImageId: !Ref BastionImageId
        BastionInstanceType: !Ref BastionInstanceType
  AppStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://umdaa-cloud-trial-trailbucket-utvblevzzv2v.s3.ap-south-1.amazonaws.com/Template/app.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.ProjectXDVpcId
        PrivateSubnet1Id: !GetAtt VPCStack.Outputs.ProjectXPrivate1
        PrivateSubnet2Id: !GetAtt VPCStack.Outputs.ProjectXPrivate2
        PrivateSubnet3Id: !GetAtt VPCStack.Outputs.ProjectXPrivate3
        PublicSubnet1Id: !GetAtt VPCStack.Outputs.ProjectXPublic1
        PublicSubnet2Id: !GetAtt VPCStack.Outputs.ProjectXPublic2
        PublicSubnet3Id: !GetAtt VPCStack.Outputs.ProjectXPublic3
        BastionSecurityGroup: !GetAtt BastionStack.Outputs.BastionSG
        KeyPairName: !Ref BastionKeyPairName
        ALBAccessCIDR: !Ref ALBAccessCIDR
        BuildAgilePartnerCert: !Ref BuildAgilePartnerCert
        AgilePartnerCert: !Ref AgilePartnerCert
        AppImageId: !Ref AppImageId
        AppInstanceType: !Ref AppInstanceType
        OperatorEMail: !Ref OperatorEMail
  RDSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://umdaa-cloud-trial-trailbucket-utvblevzzv2v.s3.ap-south-1.amazonaws.com/Template/rds.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.ProjectXDVpcId
        PrivateSubnet1Id: !GetAtt VPCStack.Outputs.ProjectXPrivate1
        PrivateSubnet2Id: !GetAtt VPCStack.Outputs.ProjectXPrivate2
        PrivateSubnet3Id: !GetAtt VPCStack.Outputs.ProjectXPrivate3
        DBInstanceClass: !Ref DBInstanceClass
        DBAllocatedStorage: !Ref DBAllocatedStorage
        DBName: !Ref DBName
        DBUser: !Ref DBUser
        DBPassword: !Ref DBPassword
        MultiAZDatabase: !Ref MultiAZDatabase
